task2:
	python bin/bfr.py data/bfr_test2 10 output/bfrtest.out output/bfrtest_int.out
task1:
	python bin/kmeans.py data/kmeans_data0.txt 3 output/kmeans.out
clean:
	rm -f output/*
	rm -rf bin/__pycache__